"""
Quran Audio-to-Ayah Indexer

A forced-alignment pipeline that produces per-ayah timestamps for Quran recitations.
The canonical Uthmani text is an INPUT, never generated by any model.
"""

__version__ = "0.1.0"
